const ACTION_TYPES = {
  LOADED_DATA   : 'LOADED_DATA',
  ADD           : 'ADD',
  UPDATE        : 'UPDATE',
  DELETE        : 'DELETE',
  TOGGLE_ALL    : 'TOGGLE_ALL',
  SHOW_ALL      : 'SHOW_ALL',
  SHOW_ACTIVE   : 'SHOW_ACTIVE',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
};

export {
  ACTION_TYPES
};